beginning of zsh switch

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -40,14 +40,14 @@ sub_update () {
 
 sub_osx () {
   for DEFAULTS_FILE in "$DOTFILES_DIR"/osx/defaults*.sh; do
-    echo "Applying $DEFAULTS_FILE" && . "$DEFAULTS_FILE"
+    echo "Applying $DEFAULTS_FILE" && source "$DEFAULTS_FILE"
   done
   echo "Done. Some changes may require a logout/restart to take effect."
 }
 
 sub_install () {
   local SCRIPT="$DOTFILES_DIR/install/$SUB_COMMAND_NAME.sh"
-  [ -f "$SCRIPT" ] && . "$SCRIPT" || echo "Unable to find script to install $SUB_COMMAND_NAME"
+  [ -f "$SCRIPT" ] && source "$SCRIPT" || echo "Unable to find script to install $SUB_COMMAND_NAME"
 }
 
 # Make sure to keep this in sync with the available public commands
